algoritmo "login e senha banco"
// Login/Senha (OPERADOR E)
var
 loginBanco: caractere
 senhaBanco: numerico

inicio
// VALORES EXISTENTES NO BANCO DE DADOS (BACK-END)
escreva ("loginBanco: ")
leia (loginBanco)

escreva ("senhaBanco: ")
leia (senhaBanco)

se (loginBanco = "thiagoribeiro") e (senhaBanco = 123) entao
   escreval ("acesso autorizado :)")
senao
    escreva ("acesso negado :(")

   

fimse




fimalgoritmo
