algoritmo "Clubes"

var
clube: caractere

inicio
escreva ("Digite o nome do clube:")
leia (clube)

     se (clube="São Paulo") entao
     escreva ("Tricolor")

senao

     se(clube="Palmeiras") entao
     escreva ("porco")

senao

     se(clube="Corinthians") entao
    escreva ("Timão")
senao
      se (clube="Santos") entao
       escreva("Peixe")
senao
       escreva("Clube desconhecido")

       fimse
    fimse
  fimse
fimse
   



fimalgoritmo
