algoritmo "loop PARA"
// Função :
// Autor :
// Data : 04/03/2022
// Seção de Declarações
var
nome: caractere
idade, contador: inteiro
inicio
// Seção de Comandos

para contador de 1 ate 3 faca
     // ENTRADAS
     escreva("Informe o nome: ")
     leia(nome)
     escreva ("Informe a idade: ")
     leia(idade)


       //SAÍDA
       escreval() // apenas para pular linha
       escreval("Nome: ",nome, " - Idade: ",idade)
       escreval() // apenas para pular linha
 fimpara

fimalgoritmo
