algoritmo "semnome"
// Função :
// Autor :
// Data : 25/02/2022
// Seção de Declarações
var
nomeCurso, descricao, unidade: caractere
contador: inteiro
inicio
//Inicializa a variável contadora

contador <- 1

//Loop ENQUANTO
enquanto (contador < 7) faca
   escreva("Nome do curso: ")
   leia(nomeCurso)
   escreva("Descrição: ")
   leia(descricao)
   escreva("Unidade: ")
   leia(unidade)

   escreval()







   contador <- contador + 1

fimenquanto

fimalgoritmo
