algoritmo "Operador NÃO (NEGAÇÃO)"
// Função: INVERTE A LÓGICA
var
blackFriday: logico // VERDADEIRO OU FALSO
inicio
      // PROCESSAMENTO DE VARIAVEIS E CONSTANTES
      blackFriday <- falso
      
      // SE BLACKFRIDAY NÃO É VERDADEIRO
      se nao(blackFriday)entao
           escreva("Não estamos na black friday...:(")

      senao
           escreva ("estamos na black fryday...:D")
           fimse
           
      

fimalgoritmo
